#export PATH="./bin:$HOME/.rbenv/shims:/usr/local/bin:/usr/local/sbin:$HOME/.sfs:$ZSH/bin:$PATH"
export PATH="./bin:/usr/local/bin:/usr/local/sbin:$HOME/.sfs:$ZSH/bin:/usr/local/share/npm/bin:$PATH"
export PATH="$JAVA_HOME/bin:$PATH"
export PATH="$HOME/dev/c1/mdi/core/scripts:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export NODE_PATH="/usr/local/lib/node_modules"
export JAVA_HOME="/Library/Java/Home"
export APACHE_HOME="/usr/local/apache2"
