#export PATH="./bin:$HOME/.rbenv/shims:/usr/local/bin:/usr/local/sbin:$HOME/.sfs:$ZSH/bin:$PATH"
export PATH="./bin:/usr/local/bin:/usr/local/sbin:$HOME/.sfs:$ZSH/bin:/usr/local/share/npm/bin:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export NODE_PATH="/usr/local/lib/node_modules"
export APACHE_HOME="/usr/local/apache2"
export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java"
